function [scenario] = createDrivingScenario()
% Copyright 2020 The MathWorks, Inc.
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 17-Jun-2020 13:50:15

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [19.8 -19.2 0;
    42 4.8 0;
    30.2 5.8 0;
    6.7 18.9 0;
    -3.8 -10.8 0;
    7.7 -25.6 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle


